import type { Column } from "../components/common/DataTable";

export function printReport(
  title: string,
  rows: any[],
  columns: Column<any>[]
) {
  const printWindow = window.open("", "_blank");

  if (!printWindow) return;

  const headers = columns
    .map((column) => `<th>${column.header}</th>`)
    .join("");

  const body = rows
    .map((row) => {
      const cells = columns
        .map((column) => {
          let value = "";

          if (column.render) {
            value = String(column.render(row));
          } else if (column.accessor) {
            value = String(row[column.accessor] ?? "");
          }

          return `<td>${value}</td>`;
        })
        .join("");

      return `<tr>${cells}</tr>`;
    })
    .join("");

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
<title>${title}</title>

<style>

body{
    font-family:Arial,sans-serif;
    padding:40px;
}

h1{
    margin:0;
}

h2{
    margin-top:5px;
    color:#444;
}

p{
    margin-bottom:20px;
}

table{
    width:100%;
    border-collapse:collapse;
}

th,td{
    border:1px solid #999;
    padding:8px;
    text-align:left;
}

th{
    background:#ececec;
}

.footer{
    margin-top:30px;
    font-size:14px;
    color:#666;
}

</style>

</head>

<body>

<h1>Jelyco Warehouse Management System</h1>

<h2>${title}</h2>

<p>
<strong>Date Printed:</strong>
${new Date().toLocaleString()}
</p>

<table>

<thead>

<tr>

${headers}

</tr>

</thead>

<tbody>

${body}

</tbody>

</table>

<div class="footer">

<p><strong>Total Records:</strong> ${rows.length}</p>

<p>Generated by Jelyco Warehouse Management System</p>

</div>

</body>

</html>
`);

  printWindow.document.close();

  printWindow.focus();

  printWindow.print();

  printWindow.close();
}